global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kafka-cluster'

scrape_configs:
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 10s

  - job_name: 'app_metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 10s
    metrics_path: '/metrics'

